# Generated by Django 5.2.11 on 2026-02-20 10:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional hero title. If empty, page title is used.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        help_text="Short subtitle or tagline for the hero section.",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "cta_title",
                    models.CharField(
                        blank=True, default="Ready to Get Started?", max_length=255
                    ),
                ),
                (
                    "cta_text",
                    models.TextField(
                        blank=True, default="Book your appliance repair service today."
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(blank=True, default="Book Now", max_length=50),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
