# Generated by Django 5.2.11 on 2026-02-20 10:49

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        default="Appliance Repair Services",
                        help_text="Main heading for the services page",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="Expert repair for all major appliances. Fast, reliable, and affordable service.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Post date")),
                ("intro", models.CharField(max_length=250)),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Short description for service cards (1-2 lines)",
                        max_length=150,
                    ),
                ),
                ("hero_usp", models.TextField(blank=True, verbose_name="Hero USP")),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Main Content"
                    ),
                ),
                (
                    "problems_we_fix",
                    wagtail.fields.StreamField(
                        [("problem", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "full title"},
                            )
                        },
                    ),
                ),
                (
                    "why_choose_us",
                    wagtail.fields.StreamField(
                        [("benefit", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.TextBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1)]],
                                {},
                            ),
                        },
                        verbose_name="Why Choose Us",
                    ),
                ),
                (
                    "faq",
                    wagtail.fields.StreamField(
                        [("faq_item", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.TextBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 0), ("answer", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["-date"], name="services_se_date_8877fc_idx")
                ],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServiceRelatedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_services",
                        to="services.servicepage",
                    ),
                ),
                (
                    "related_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
