# Generated by Django 5.2.10 on 2026-03-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="author_name",
            field=models.CharField(
                blank=True,
                help_text="Author name (uses business name if blank). Improves E-E-A-T signals.",
                max_length=100,
            ),
        ),
    ]
