# Generated by Django 5.2.11 on 2026-02-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        default="LOWL Appliance Repair",
                        help_text="Business name shown in header, footer, and SEO",
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Same-Day Appliance Repair",
                        help_text="Short tagline shown in hero section",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+15550001234",
                        help_text="Primary phone number (with country code)",
                        max_length=20,
                    ),
                ),
                (
                    "phone_display",
                    models.CharField(
                        blank=True,
                        default="(555) 000-1234",
                        help_text="Phone number as displayed to users",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="info@example.com", max_length=254
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                (
                    "city",
                    models.CharField(blank=True, default="Placentia", max_length=100),
                ),
                ("state", models.CharField(blank=True, default="CA", max_length=2)),
                (
                    "zip_code",
                    models.CharField(blank=True, default="92870", max_length=10),
                ),
                (
                    "booking_url",
                    models.URLField(
                        blank=True,
                        help_text="External booking system URL (UTM params will be appended automatically)",
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        blank=True,
                        default="website",
                        help_text="Source parameter appended to booking URL",
                        max_length=50,
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        blank=True,
                        default="8:00 AM - 8:00 PM",
                        help_text="Operating hours displayed on the site",
                        max_length=100,
                    ),
                ),
                (
                    "warranty_days",
                    models.PositiveIntegerField(
                        default=90, help_text="Warranty period in days"
                    ),
                ),
                (
                    "service_call_fee",
                    models.PositiveIntegerField(
                        default=70, help_text="Diagnostic/service call fee in dollars"
                    ),
                ),
                (
                    "labor_rate_min",
                    models.PositiveIntegerField(
                        default=120, help_text="Minimum labor rate in dollars"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics 4 Measurement ID (e.g. G-XXXXXXXXXX)",
                        max_length=30,
                    ),
                ),
                (
                    "gtm_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Tag Manager ID (e.g. GTM-XXXXXXX)",
                        max_length=30,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
    ]
