# Generated by Django 5.2.11 on 2026-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="booking_url",
            field=models.URLField(
                blank=True,
                default="https://lowl-booking-production.up.railway.app/",
                help_text="External booking system URL (UTM params will be appended automatically)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(
                blank=True, default="info@lowl.net", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(
                blank=True,
                default="+19516209609",
                help_text="Primary phone number (with country code)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_display",
            field=models.CharField(
                blank=True,
                default="(951) 620-9609",
                help_text="Phone number as displayed to users",
                max_length=30,
            ),
        ),
    ]
