# Generated by Django 5.2.11 on 2026-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_update_defaults_real_business_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="warranty_days",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="warranty_text",
            field=models.CharField(
                blank=True,
                default="Warranty Included",
                help_text="Warranty label displayed on the site (e.g. 'Warranty Included', '90-Day Warranty')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_line1",
            field=models.CharField(
                blank=True, default="409 N Langstaff St", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_line2",
            field=models.CharField(blank=True, default="Ste A", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="city",
            field=models.CharField(blank=True, default="Lake Elsinore", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="zip_code",
            field=models.CharField(blank=True, default="92530", max_length=10),
        ),
    ]
