# Generated by Django 5.2.10 on 2026-03-04 21:12

from django.db import migrations, models


def update_existing_booking_source(apps, schema_editor):
    """Update existing SiteSettings records from 'website' to 'lowl'."""
    SiteSettings = apps.get_model("home", "SiteSettings")
    SiteSettings.objects.filter(booking_source="website").update(booking_source="lowl")


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_warranty_text_and_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="booking_source",
            field=models.CharField(
                blank=True,
                default="lowl",
                help_text="Source parameter appended to booking URL (e.g. 'lowl', 'profix')",
                max_length=50,
            ),
        ),
        migrations.RunPython(update_existing_booking_source, migrations.RunPython.noop),
    ]
