# Generated by Django 5.2.10 on 2026-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_change_booking_source_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=4.9,
                help_text="Average Google review rating (e.g. 4.9)",
                max_digits=2,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_review_count",
            field=models.PositiveIntegerField(
                default=150, help_text="Total number of Google reviews"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=33.668045,
                help_text="Business latitude for Google Maps (e.g. 33.668045)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=-117.327354,
                help_text="Business longitude for Google Maps (e.g. -117.327354)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
