# Generated by Django 5.2.10 on 2026-03-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_add_seo_fields_to_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bing_site_verification",
            field=models.CharField(
                blank=True,
                help_text="Bing Webmaster Tools verification code",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                help_text="Google Search Console verification code (just the content value)",
                max_length=100,
            ),
        ),
    ]
