# Generated by Django 5.2.10 on 2026-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_add_search_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(blank=True, help_text="Facebook business page URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_business_url",
            field=models.URLField(
                blank=True,
                help_text="Google Business Profile URL (e.g. https://g.co/kgs/...)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="yelp_url",
            field=models.URLField(blank=True, help_text="Yelp business page URL"),
        ),
    ]
