# Generated by Django 5.2.10 on 2026-03-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_add_social_profile_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="closing_time",
            field=models.TimeField(
                default="20:00",
                help_text="Daily closing time for structured data (e.g. 20:00)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="opening_time",
            field=models.TimeField(
                default="08:00",
                help_text="Daily opening time for structured data (e.g. 08:00)",
            ),
        ),
    ]
