# Generated by Django 5.2.11 on 2026-03-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_add_opening_closing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="address_line1",
            field=models.CharField(
                blank=True, default="632 Shadybrook Ln", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="city",
            field=models.CharField(blank=True, default="Corona", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(
                blank=True, default="inlandrepair.ca@gmail.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(
                blank=True,
                default="+19099752506",
                help_text="Primary phone number (with country code)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_display",
            field=models.CharField(
                blank=True,
                default="(909) 975-2506",
                help_text="Phone number as displayed to users",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="zip_code",
            field=models.CharField(blank=True, default="92879", max_length=10),
        ),
    ]
