# Generated by Django 5.2.11 on 2026-02-20 10:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityfeaturedservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="services.servicepage",
            ),
        ),
        migrations.AddIndex(
            model_name="citypage",
            index=models.Index(fields=["state"], name="locations_c_state_dbdb7c_idx"),
        ),
        migrations.AddField(
            model_name="citynearbycity",
            name="nearby_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="locations.citypage",
            ),
        ),
        migrations.AddField(
            model_name="citynearbycity",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearby_cities",
                to="locations.citypage",
            ),
        ),
        migrations.AddField(
            model_name="cityfeaturedservice",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_services",
                to="locations.citypage",
            ),
        ),
    ]
