# Generated by Django 5.2.10 on 2026-03-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="citypage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Featured image for OG/social sharing (1200x630 recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
